name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "news-db"
database_id = "9496155b-83e2-45e2-826a-f74f23f9e602"
